### ISSUE TITLE
NPE when braking a sign

### ISSUE THREAD

**Issue by mormoon** [kangarko/Winter#11]
Steps to reproduce.
1) place a sign with random text
2) brake the sign

`[21:18:35] [Server thread/INFO]: Winter // Winter 1.1.0 encountered a COM3! Please check your error.log and report this issue with the information in that file.
[21:18:35] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Winter v1.1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:889) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: me.kangarko.winter.final. .COM3: Report / chest == null
        at me.kangarko.winter.final. .LPT9.const(SourceFile:20) ~[Winter-1.1.0.jar:?]
        at me.kangarko.winter.final. .nUl.const(SourceFile:94) ~[Winter-1.1.0.jar:?]
        at me.kangarko.winter.final. .nUl.native(SourceFile:90) ~[Winter-1.1.0.jar:?]
        at me.kangarko.winter.final. .Aux.onBlockBreak(SourceFile:256) ~[Winter-1.1.0.jar:?]
        at sun.reflect.GeneratedMethodAccessor211.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
        ... 17 more
`

**Comment by kangarko** [comment]
Thanks, fixed.
