### ISSUE TITLE
Snow particles no longer working on 1.1.5

### ISSUE THREAD

**Issue by mormoon** [kangarko/Winter#17]
Since 1.1.5 snow particles is no longer working on 1.12.2.

This server is running CraftBukkit version git-Spigot-549c1fa-70cc382 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version

**Comment by PhanaticD** [comment]
same
```
IllegalArgumentExceptiondata should be class java.lang.Void got class java.lang.Double
     at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnParticle(CraftWorld.java:1574)
     at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnParticle(CraftWorld.java:1553)
     at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnParticle(CraftWorld.java:1533)
     at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnParticle(CraftWorld.java:1528)
     at me.kangarko.winter.final. .coM1.const(SourceFile:671)
     at me.kangarko.winter.final. .lpt8.const(SourceFile:110)
     at me.kangarko.winter.final. .lpt8.run(SourceFile:49)
     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
```

**Comment by Fader-GumGum** [comment]
Same:


------------------------------------[ 12.12.2017 19:18:04 ]-----------------------------------
Winter 1.1.5 encountered a IllegalArgumentException
Running 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_151
Plugins: MCGUIControlPlugin v2.6.2.1, SkyVote v1.0.8, PlaceholderAPI v2.8.2, MobEggSpawnerBlocker v1, TuxTwoLib v1.11-b8, AntiAFKPlus v2.11, Winter v1.1.5, GeneralLib v0.1.4, BanManager v5.15.0, SpectatorDisabler v1.5.0, TitleAPI v1.7.5, DiscordChat v1.3, MC-Cron v1.2, NoobResponse v3.03, TrophyHeads v1.12.7-46, SimpleHoloChat v1.0.0, CoreProtect v2.14.2, dynmap v2.6-SNAPSHOT-Dev201710222207, LuckPerms v4.0.42, IPSecurity v1.1, MultiInv v3.3.10, ClearLag v2.9.7, AutoMessage v2.5.5, CrackShot v0.98.7, WorldBorder v1.8.7, Votifier v2.3.5, ProtocolLib v4.4.0-SNAPSHOT-b390, dynmap-mobs v1.3, VotingPlugin v5.11, FastAsyncWorldEdit v17.10.16-7a4b7be-936-17.0.19, EnchantLimit v2.2, BlocksHub v2.1.1, AngryWolves v2.4-SNAPSHOT-61, Vault v1.5.6-b49, TimeVote v1.31, MassiveCore v2.13.2, AntiCommandTab v3.4, LWC v1.9.3, WorldPortal v0.2.7.1, WorldEdit v6.1.8-SNAPSHOT;3696-82bf563, Essentials v2.0.1-bSNAPSHOT, Citizens v2.0.22-SNAPSHOT (build 1496), Sentinel v1.4.5 (build 156), EasyKits v2.0.3, OnTime v4.1.4, CloneMe v2.6.1, EssentialsChat v2.0.1-bSNAPSHOT, EnjinMinecraftPlugin v3.4.3, Dynmap-Citizens2 v0.30, WorldEditSelectionVisualizer v1.4.8, Dynmap-Essentials v0.91-SNAPSHOT, PlotSquared v17.12.09-59557cf-1945, WorldGuard v6.2.2-SNAPSHOT;1708-3a8e3e8, SkyWars v2.2.0, EssentialsProtect v2.0.1-bSNAPSHOT, EssentialsGeoIP v2.0.1-bSNAPSHOT, EssentialsAntiBuild v2.0.1-bSNAPSHOT, StaffList v3.5, EssentialsSpawn v2.0.1-bSNAPSHOT, RedstoneClockPreventer v1.3.1, TitleManager v2.0.9, CompatNoCheatPlus v6.6.4-RC-sMD5NET-b88, Dynmap-WorldGuard v0.90, The Multiverse-Core Plugin, Plot2Dynmap v3.3.1, CraftBook v3.9-SNAPSHOT-jenkins-CraftBook-191, GriefPrevention v16.7.1, ChestShop v3.8.13-SNAPSHOT (build #41), AuthMe v5.4.0-b1877, MobArena v0.99, HolographicDisplays v2.2.6, Holograms v2.5.0-SNAPSHOT, SkinsRestorer v13.1.4, Factions v2.13.2, MysqlEconomyBank v1.10.1, RandomTeleport v5.16.2, CratesPlus v4.4.4, WirelessRedstone v3.0.5, PlayerStatusSigns v2.1.3, MobHunting v5.2.1, ChatControl v7.6.24, Kingdoms v13.2.40, Plan v4.1.3.1, DeathChest v3.5, JDynmapGriefPrevention v2.5.1, FactionChat v1.10.7, Lift v56, NoCheatPlus v3.15.2-SNAPSHOT-sMD5NET-b1113, Signs v1.9.7, Laser v3.5.19
----------------------------------------------------------------------------------------------

More Information: 
Error showing snow particles!
Stopping task for safety.
%error
IllegalArgumentExceptiondata should be class java.lang.Void got class java.lang.Double
	 at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnParticle(CraftWorld.java:1528)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnParticle(CraftWorld.java:1507)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnParticle(CraftWorld.java:1487)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnParticle(CraftWorld.java:1482)
	 at me.kangarko.winter.final. .coM1.const(SourceFile:671)
	 at me.kangarko.winter.final. .lpt8.const(SourceFile:110)
	 at me.kangarko.winter.final. .lpt8.run(SourceFile:49)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Confirmed. Will be fixed asap.
