### ISSUE TITLE
Need Java 15 Support

### ISSUE THREAD

**Issue by rudde0** [kangarko/Winter#21]
```
[19:58:47] [Server thread/INFO]: [Winter] Enabling Winter v2.5.2
[19:58:47] [Server thread/INFO]: _ _ _ _ _  _ ___ ____ ____[m
[19:58:47] [Server thread/INFO]: | | | | |\ |  |  |___ |__/[m
[19:58:47] [Server thread/INFO]: |_|_| | | \|  |  |___ |  \[m
[19:58:47] [Server thread/INFO]:   [m
[19:58:47] [Server thread/INFO]: Get Support:[m
[19:58:47] [Server thread/INFO]: https://github.com/kangarko/Winter/issues[m
[19:58:47] [Server thread/INFO]: ______________________________________________________________[m
[19:58:47] [Server thread/INFO]: !-----------------------------------------------------![m
[19:58:47] [Server thread/INFO]: JavaScript placeholders will not function![m
[19:58:47] [Server thread/INFO]:   [m
[19:58:47] [Server thread/INFO]: Your Java version/distribution lacks the[m
[19:58:47] [Server thread/INFO]: Nashorn library for JavaScript placeholders.[m
[19:58:47] [Server thread/INFO]: Please install Oracle Java 8 JDK.[m
[19:58:47] [Server thread/INFO]: Plugin is now disabled.[m
[19:58:47] [Server thread/INFO]: !-----------------------------------------------------![m
[19:58:47] [Server thread/INFO]: [Winter] Disabling Winter v2.5.2
[19:58:47] [Server thread/INFO]: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.getBindings(int)" because "org.mineacademy.winter.lib.fo.model.JavaScriptExecutor.engine" is null
[19:58:47] [Server thread/INFO]: 	at org.mineacademy.winter.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:112)
[19:58:47] [Server thread/INFO]: 	at org.mineacademy.winter.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:75)
[19:58:47] [Server thread/INFO]: 	at org.mineacademy.winter.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:348)
[19:58:47] [Server thread/INFO]:     ___                  _[m
[19:58:47] [Server thread/INFO]:    / _ \  ___  _ __  ___| |[m
[19:58:47] [Server thread/INFO]:   | | | |/ _ \| '_ \/ __| |[m
[19:58:47] [Server thread/INFO]:   | |_| | (_) | |_) \__ \_|[m
[19:58:47] [Server thread/INFO]:    \___/ \___/| .__/|___(_)[m
[19:58:47] [Server thread/INFO]:              |_|[m
[19:58:47] [Server thread/INFO]: !-----------------------------------------------------![m
[19:58:47] [Server thread/INFO]: Error loading Winter v2.5.2, plugin is disabled![m
[19:58:47] [Server thread/INFO]: Running on 1.16.4-R0.1-SNAPSHOT (v1_16_R3) & Java 15.0.1[m
[19:58:47] [Server thread/INFO]: !-----------------------------------------------------![m
[19:58:47] [Server thread/INFO]: Error: Cannot invoke "javax.script.ScriptEngine.getBindings(int)" because "org.mineacademy.winter.lib.fo.model.JavaScriptExecutor.engine" is null[m
[19:58:47] [Server thread/INFO]: !-----------------------------------------------------![m
```

**Comment by kangarko** [comment]
I understand, we're planning to add J15 support when MC 1.17 is out
