### ISSUE TITLE
Error when player teleports to some location

### ISSUE THREAD

**Issue by UBERScholes** [kangarko/Winter#39]
I have Paper 1.12 and I have an error when player teleports somewhere

[22:25:36 WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.MCUtil.ensureMain(MCUtil.java:51)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getChunkAt(CraftWorld.java:174)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
[22:25:36 WARN]:        at me.kangarko.winter.final. .f.const(SourceFile:128)
[22:25:36 WARN]:        at me.kangarko.winter.final. .f.const(SourceFile:111)
[22:25:36 WARN]:        at me.kangarko.winter.final. .f.run(SourceFile:72)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:25:36 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:25:36 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:25:36 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:25:36 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:25:36 WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.MCUtil.ensureMain(MCUtil.java:51)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getChunkAt(CraftWorld.java:174)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
[22:25:36 WARN]:        at me.kangarko.winter.final. .f.const(SourceFile:128)
[22:25:36 WARN]:        at me.kangarko.winter.final. .f.const(SourceFile:111)
[22:25:36 WARN]:        at me.kangarko.winter.final. .f.run(SourceFile:72)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:25:36 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:25:36 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:25:36 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:25:36 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:25:36 WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.MCUtil.ensureMain(MCUtil.java:51)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[22:25:36 WARN]:        at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getChunkAt(CraftWorld.java:174)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
[22:25:36 WARN]:        at me.kangarko.winter.final. .f.const(SourceFile:128)
[22:25:36 WARN]:        at me.kangarko.winter.final. .f.const(SourceFile:111)
[22:25:36 WARN]:        at me.kangarko.winter.final. .f.run(SourceFile:72)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[22:25:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:25:36 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:25:36 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:25:36 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:25:36 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by kangarko** [comment]
Please test using the next version and re-post if it appears.

**Comment by TheoRetisch1** [comment]
I have the same problem with the latest version. It doesn't happen after every teleport but often enough. 
The error appears but everything works fine.
Winter: 1.5.3
PaperSpigiot 1.12.2 #1593
error: https://pastebin.com/Yib1DnS4

**Comment by kangarko** [comment]
Upgrade to the next version please
