### ISSUE TITLE
error after removing plugin Whole world makes everytime on everyplace errors.... given money for damaging my world?

### ISSUE THREAD

**Issue by Nudelstern** [kangarko/Winter#41]
[17:10:58 WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_13_R2.TileEntityCommand@73c86951) at -278,80,92 (minecraft:grass_block[snowy=false]) where there was no entity tile!
[17:10:58 WARN]: Chunk coordinates: -288,80
[17:10:58 WARN]:        at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:880)
[17:10:58 WARN]:        at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:853)
[17:10:58 WARN]:        at net.minecraft.server.v1_13_R2.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:825)
[17:10:58 WARN]:        at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.postChunk(PaperAsyncChunkProvider.java:463)
[17:10:58 WARN]:        at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processChunkLoads(PaperAsyncChunkProvider.java:101)
[17:10:58 WARN]:        at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processChunkLoads(PaperAsyncChunkProvider.java:87)
[17:10:58 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1112)
[17:10:58 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[17:10:58 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[17:10:58 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[17:10:58 WARN]:        at java.lang.Thread.run(Thread.java:748)

@EVERY CHUNK is loaded

**Comment by kangarko** [comment]
Please report to https://github.com/PaperMC/Paper/issues. It unlikely that we caused damage unless you used /wt populate command and interrupted it in the middle of the process. Did you use that command?

**Comment by Nudelstern** [comment]
server crashed after i choose in config to thaw all the snow. While this is happend it crashed and never continued with thawing, Also i have every chunk this error above

**Comment by kangarko** [comment]
Have you reported this to the Paper community?

**Comment by Nudelstern** [comment]
i dont got an answer

**Comment by Nudelstern** [comment]
its repaired by generating new world and copy paste buildings.. but i dont wanna use it anymore. and also this issue has been reported by other when i´ve readed it right.

**Comment by kangarko** [comment]
Okay thank you for reporting, let me know when your issue is answered so I can also notify other users of Winter that they should update Paper.
