### ISSUE TITLE
java.lang.NoSuchFieldError: FARMLAND

### ISSUE THREAD

**Issue by ASCIIcat** [kangarko/Winter#44]
I have the following enabled in the config
`Destroy_Crops: true`
However, this causing the following to be spammed in the console:
```
java.lang.NoSuchFieldError: FARMLAND
at me.kangarko.winter.final. .g.run(SourceFile:53) ~[Winter-1.5.5.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```
This is on 1.12.2

**Comment by kangarko** [comment]
Thanks, fixed.
