### ISSUE TITLE
1.18.1: Exception while using Winter Populate

### ISSUE THREAD

**Issue by yuzhang-io** [kangarko/Winter#58]
Getting errors while trying to use winter populate add command. Running Paper version `git-Paper-"5ad1d9a" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5ad1d9a)` with `Winter 3.0.6 `

Console Log:
```17.12 11:23:48 [Server] INFO [Winter] 1/3 Kicking all players & enabling whitelist ...
17.12 11:23:48 [Server] INFO [Winter] 2/3 Running region scan ...
17.12 11:23:48 [Server] INFO [Winter] !-----------------------------------------------------!
17.12 11:23:48 [Server] INFO [Winter] Scanning regions in --- 
17.12 11:23:48 [Server] INFO [Winter] !-----------------------------------------------------!
17.12 11:23:48 [Server] INFO [Winter 3.0.6] Command /winter populate add --- took 154.29 ms
17.12 11:23:48 [Server] Startup[0%] Processing ./---/region/r.15.17.mca
17.12 11:23:48 [Server]  [Winter] Task #7851 for Winter v3.0.6 generated an exception
17.12 11:23:48 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.winter.lib.fo.model.RegionAccessor
17.12 11:23:48 [Server] INFO at org.mineacademy.winter.lib.fo.model.OfflineRegionScanner.scanFile(OfflineRegionScanner.java:232) ~[Winter-3.0.6.jar:?]
17.12 11:23:48 [Server] INFO at org.mineacademy.winter.lib.fo.model.OfflineRegionScanner.access$200(OfflineRegionScanner.java:33) ~[Winter-3.0.6.jar:?]
17.12 11:23:48 [Server] INFO at org.mineacademy.winter.lib.fo.model.OfflineRegionScanner$1.run(OfflineRegionScanner.java:193) ~[Winter-3.0.6.jar:?]
17.12 11:23:48 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
17.12 11:23:48 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
17.12 11:23:48 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
17.12 11:23:48 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
17.12 11:23:48 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
17.12 11:23:48 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
17.12 11:23:48 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
17.12 11:23:48 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]```

**Comment by kangarko** [comment]
Did you use plugman or have reloaded winter since? Going to test this asap in 24 hours

**Comment by kangarko** [comment]
Thanks, will get patched.
