### ISSUE TITLE
1.17.1: Task #121 for Winter

### ISSUE THREAD

**Issue by MonkaMaczna** [kangarko/Winter#64]
After removing using populate all of the snow and ice on the map and console is sometimes throwing the same error on the console now. 
```
[09:56:09 WARN]: [Winter] Task #121 for Winter v3.0.7 generated an exception
java.lang.IllegalArgumentException: Cannot set property BlockStateInteger{name=layers, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7, 8]} to 0 on Block{minecraft:snow}, it is not an allowed value
        at net.minecraft.world.level.block.state.IBlockDataHolder.set(IBlockDataHolder.java:111) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.set(CraftBlockData.java:196) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.craftbukkit.v1_17_R1.block.impl.CraftSnow.setLayers(CraftSnow.java:27) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.mineacademy.winter.lib.winter.model.task.TaskTerrain.run(TaskTerrain.java:98) ~[Winter-3.0.7.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1393]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

There aren't any visible problems from the side of the gameplay, but it is pretty annoying in the console.

**Comment by kangarko** [comment]
I undertand, a fix will be out in less than 24 hours, thanks!
