### ISSUE TITLE
1.21.3 Human error leads to error Unparseable date

### ISSUE THREAD

**Issue by x1p** [kangarko/Winter#92]
Making an oopsie on a sign leads to an error
```
[13:21:01 ERROR]: Could not pass event PlayerInteractEvent to Winter v4.1.3
org.mineacademy.winter.lib.exception.FoException: Report: java.text.ParseException: Unparseable date: "24"
at Winter-4.1.3.jar/org.mineacademy.winter.chest.InfiniteChest.parseDate(InfiniteChest.java:73) ~[Winter-4.1.3.jar:?]
at Winter-4.1.3.jar/org.mineacademy.winter.chest.DatedChest.make(DatedChest.java:114) ~[Winter-4.1.3.jar:?]
at Winter-4.1.3.jar/org.mineacademy.winter.util.GiftSignUtil.constructChest(GiftSignUtil.java:116) ~[Winter-4.1.3.jar:?]
at Winter-4.1.3.jar/org.mineacademy.winter.util.GiftSignUtil.findChestStrict(GiftSignUtil.java:67) ~[Winter-4.1.3.jar:?]
at Winter-4.1.3.jar/org.mineacademy.winter.util.GiftSignUtil.findChestFull(GiftSignUtil.java:48) ~[Winter-4.1.3.jar:?]
at Winter-4.1.3.jar/org.mineacademy.winter.listener.ChestListener.handleChestOpen(ChestListener.java:186) ~[Winter-4.1.3.jar:?]
at Winter-4.1.3.jar/org.mineacademy.winter.listener.ChestListener.onChestOpen(ChestListener.java:177) ~[Winter-4.1.3.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:603) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:544) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2034) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1620) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1597) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1590) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:117) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1740) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1368) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.text.ParseException: Unparseable date: "24"
at java.base/java.text.DateFormat.parse(DateFormat.java:399) ~[?:?]
at Winter-4.1.3.jar/org.mineacademy.winter.chest.InfiniteChest.parseDate(InfiniteChest.java:71) ~[Winter-4.1.3.jar:?]
... 32 more
[13:21:01 INFO]: java.lang.NoSuchMethodError: 'void io.sentry.SentryOptions.setEnableUncaughtExceptionHandler(boolean)'
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.debug.Debugger.lambda$saveError$1(Debugger.java:121)
[13:21:01 INFO]: at io.sentry.Sentry.init(Sentry.java:139)
[13:21:01 INFO]: at io.sentry.Sentry.init(Sentry.java:126)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.debug.Debugger.lambda$saveError$2(Debugger.java:118)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore$1.run(CommonCore.java:1755)
[13:21:01 INFO]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore.wrapRunnableInExceptionCatcher(CommonCore.java:1748)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.remain.Remain.runTaskAsync(Remain.java:2862)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.platform.BukkitPlatform.runTaskAsync(BukkitPlatform.java:633)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.platform.FoundationPlatform.runTaskAsync(FoundationPlatform.java:227)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.platform.Platform.runTaskAsync(Platform.java:338)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.debug.Debugger.saveError(Debugger.java:115)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.exception.FoException.<init>(FoException.java:32)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.chest.InfiniteChest.parseDate(InfiniteChest.java:73)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.chest.DatedChest.make(DatedChest.java:114)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.util.GiftSignUtil.constructChest(GiftSignUtil.java:116)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.util.GiftSignUtil.findChestStrict(GiftSignUtil.java:67)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.util.GiftSignUtil.findChestFull(GiftSignUtil.java:48)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.listener.ChestListener.handleChestOpen(ChestListener.java:186)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.listener.ChestListener.onChestOpen(ChestListener.java:177)
[13:21:01 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source)
[13:21:01 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:21:01 INFO]: at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:21:01 INFO]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[13:21:01 INFO]: java.lang.NoSuchMethodError: 'void io.sentry.SentryOptions.setEnableUncaughtExceptionHandler(boolean)'
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.debug.Debugger.lambda$saveError$1(Debugger.java:121)
[13:21:01 INFO]: at io.sentry.Sentry.init(Sentry.java:139)
[13:21:01 INFO]: at io.sentry.Sentry.init(Sentry.java:126)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.debug.Debugger.lambda$saveError$2(Debugger.java:118)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore$1.run(CommonCore.java:1755)
[13:21:01 INFO]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore.wrapRunnableInExceptionCatcher(CommonCore.java:1748)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.remain.Remain.runTaskAsync(Remain.java:2862)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.platform.BukkitPlatform.runTaskAsync(BukkitPlatform.java:633)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.platform.FoundationPlatform.runTaskAsync(FoundationPlatform.java:227)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.platform.Platform.runTaskAsync(Platform.java:338)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.debug.Debugger.saveError(Debugger.java:115)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore.logCombinedError(CommonCore.java:1794)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore.access$000(CommonCore.java:51)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore$1.run(CommonCore.java:1758)
[13:21:01 INFO]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:21:01 INFO]: java.lang.NoSuchMethodError: 'void io.sentry.SentryOptions.setEnableUncaughtExceptionHandler(boolean)'
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.debug.Debugger.lambda$saveError$1(Debugger.java:121)
[13:21:01 INFO]: at io.sentry.Sentry.init(Sentry.java:139)
[13:21:01 INFO]: at io.sentry.Sentry.init(Sentry.java:126)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.debug.Debugger.lambda$saveError$2(Debugger.java:118)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore$1.run(CommonCore.java:1755)
[13:21:01 INFO]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore.wrapRunnableInExceptionCatcher(CommonCore.java:1748)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.remain.Remain.runTaskAsync(Remain.java:2862)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.platform.BukkitPlatform.runTaskAsync(BukkitPlatform.java:633)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.platform.FoundationPlatform.runTaskAsync(FoundationPlatform.java:227)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.platform.Platform.runTaskAsync(Platform.java:338)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.debug.Debugger.saveError(Debugger.java:115)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore.logCombinedError(CommonCore.java:1794)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore.access$000(CommonCore.java:51)
[13:21:01 INFO]: at Winter-4.1.3.jar//org.mineacademy.winter.lib.CommonCore$1.run(CommonCore.java:1758)
[13:21:01 INFO]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
```

**Comment by kangarko** [comment]
Thanks, will be fixed.
